name: starter_template
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.0.0

dependencies:
  appwrouter:
    git:
      url: https://github.com/moshOntong-IT/appwrouter.git
      path: dart/appwrouter
      ref: shorten
  dart_appwrite: 11.0.1

dev_dependencies:
  lints: ^2.0.0
