name: appwrouter
description: A router for appwrite cloud functions
version: 0.1.0+1
license: MIT
homepage: https://github.com/moshOntong-IT/appwrouter/dart/appwrouter
repository: https://github.com/moshOntong-IT/appwrouter/dart/appwrouter
environment:
  sdk: "^3.3.0"

dependencies:
  appwrite: ^11.0.1

dev_dependencies:
  mocktail: ^1.0.3
  test: ^1.25.2
  very_good_analysis: ^5.1.0
